// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SiPacul.Infrastructure.Data;

#nullable disable

namespace SiPacul.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SiPaculDbContext))]
    [Migration("20260731140713_AddCropCycles")]
    partial class AddCropCycles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SiPacul.Domain.Entities.Cultivation.CropCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ActualHarvestDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ActualStartDate")
                        .HasColumnType("date");

                    b.Property<int>("AreaUnit")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("CultivationSopId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateOnly>("ExpectedHarvestDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("LandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LandPlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PlannedStartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PlantedArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("AK_CropCycles_OrganizationId_Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_CropCycles_OrganizationId_Code");

                    b.HasIndex("OrganizationId", "CommodityId")
                        .HasDatabaseName("IX_CropCycles_OrganizationId_CommodityId");

                    b.HasIndex("OrganizationId", "CultivationSopId");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("IX_CropCycles_OrganizationId_Status");

                    b.HasIndex("OrganizationId", "PlannedStartDate", "ExpectedHarvestDate")
                        .HasDatabaseName("IX_CropCycles_OrganizationId_PlannedDateRange");

                    b.HasIndex(new[] { "OrganizationId", "LandId", "LandPlotId" }, "IX_CropCycles_OrganizationId_LandId_LandPlotId")
                        .HasDatabaseName("IX_CropCycles_OrganizationId_LandId_LandPlotId");

                    b.HasIndex(new[] { "OrganizationId", "LandId", "LandPlotId" }, "UX_CropCycles_OrganizationId_LandId_LandPlotId_InProgress")
                        .IsUnique()
                        .HasDatabaseName("UX_CropCycles_OrganizationId_LandId_LandPlotId_InProgress")
                        .HasFilter("\"Status\" = 2 AND \"IsDeleted\" = FALSE");

                    b.ToTable("CropCycles", (string)null);
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Cultivation.CultivationSop", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommodityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OrganizationId", "CommodityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_CultivationSops_OrganizationId_CommodityId_Name");

                    b.HasIndex("OrganizationId", "CommodityId", "IsActive", "IsDeleted")
                        .HasDatabaseName("IX_CultivationSops_OrganizationId_CommodityId_Status");

                    b.ToTable("CultivationSops", (string)null);
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Cultivation.CultivationSopStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CultivationSopId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EstimatedDurationDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlannedDayOffset")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CultivationSopId");

                    b.HasIndex("OrganizationId", "PlannedDayOffset")
                        .HasDatabaseName("IX_CultivationSopSteps_OrganizationId_PlannedDayOffset");

                    b.ToTable("CultivationSopSteps", (string)null);
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Lands.Land", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("AreaUnit")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("LocationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("TenureType")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("AK_Lands_OrganizationId_Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Lands_OrganizationId_Code");

                    b.HasIndex("OrganizationId", "IsActive", "IsDeleted")
                        .HasDatabaseName("IX_Lands_OrganizationId_Status");

                    b.ToTable("Lands", (string)null);
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Lands.LandPlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Area")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("AreaUnit")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneralCondition")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "LandId", "Id")
                        .HasName("AK_LandPlots_OrganizationId_LandId_Id");

                    b.HasIndex("OrganizationId", "LandId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_LandPlots_OrganizationId_LandId_Code");

                    b.HasIndex("OrganizationId", "LandId", "IsActive")
                        .HasDatabaseName("IX_LandPlots_OrganizationId_LandId_Status");

                    b.ToTable("LandPlots", (string)null);
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.MasterData.Commodity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CommodityCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScientificName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Commodities_OrganizationId_Code");

                    b.HasIndex("OrganizationId", "CommodityCategoryId");

                    b.HasIndex("OrganizationId", "IsActive", "IsDeleted")
                        .HasDatabaseName("IX_Commodities_OrganizationId_Status");

                    b.ToTable("Commodities", (string)null);
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.MasterData.CommodityCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("AK_CommodityCategories_OrganizationId_Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_CommodityCategories_OrganizationId_Name");

                    b.HasIndex("OrganizationId", "IsActive", "IsDeleted")
                        .HasDatabaseName("IX_CommodityCategories_OrganizationId_Status");

                    b.ToTable("CommodityCategories", (string)null);
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Organizations_Code");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsActive", "IsDeleted")
                        .HasDatabaseName("IX_Organizations_Status");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Cultivation.CropCycle", b =>
                {
                    b.HasOne("SiPacul.Domain.Entities.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CropCycles_Organizations_OrganizationId");

                    b.HasOne("SiPacul.Domain.Entities.MasterData.Commodity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CommodityId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CropCycles_Commodities_OrganizationId_CommodityId");

                    b.HasOne("SiPacul.Domain.Entities.Cultivation.CultivationSop", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CultivationSopId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CropCycles_CultivationSops_OrganizationId_CultivationSopId");

                    b.HasOne("SiPacul.Domain.Entities.Lands.Land", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "LandId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CropCycles_Lands_OrganizationId_LandId");

                    b.HasOne("SiPacul.Domain.Entities.Lands.LandPlot", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "LandId", "LandPlotId")
                        .HasPrincipalKey("OrganizationId", "LandId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CropCycles_LandPlots_OrganizationId_LandId_LandPlotId");
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Cultivation.CultivationSop", b =>
                {
                    b.HasOne("SiPacul.Domain.Entities.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiPacul.Domain.Entities.MasterData.Commodity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CommodityId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Cultivation.CultivationSopStep", b =>
                {
                    b.HasOne("SiPacul.Domain.Entities.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiPacul.Domain.Entities.Cultivation.CultivationSop", null)
                        .WithMany("Steps")
                        .HasForeignKey("OrganizationId", "CultivationSopId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Lands.Land", b =>
                {
                    b.HasOne("SiPacul.Domain.Entities.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Lands.LandPlot", b =>
                {
                    b.HasOne("SiPacul.Domain.Entities.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiPacul.Domain.Entities.Lands.Land", null)
                        .WithMany("Plots")
                        .HasForeignKey("OrganizationId", "LandId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.MasterData.Commodity", b =>
                {
                    b.HasOne("SiPacul.Domain.Entities.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiPacul.Domain.Entities.MasterData.CommodityCategory", "CommodityCategory")
                        .WithMany("Commodities")
                        .HasForeignKey("OrganizationId", "CommodityCategoryId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommodityCategory");
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.MasterData.CommodityCategory", b =>
                {
                    b.HasOne("SiPacul.Domain.Entities.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Cultivation.CultivationSop", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.Lands.Land", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("SiPacul.Domain.Entities.MasterData.CommodityCategory", b =>
                {
                    b.Navigation("Commodities");
                });
#pragma warning restore 612, 618
        }
    }
}
